[package]
name = "md-profiler"
version = "1.1.0"
edition = "2018"

[dependencies]
serde = { version = "1.0.127", features = ["derive"] }
serde_json = "1.0.66"
clap = "2.33.3"

[profile.release]
lto = true
codegen-units = 1
